export const USER_SOCKET_CONNECTED_CHANNEL = 'USER_SOCKET_CONNECTED_CHANNEL';

export const USER_SOCKET_EVENT = {
  CONNECTED: 'connected',
  DISCONNECTED: 'disconnected'
};

export const PERFORMER_SOCKET_CONNECTED_CHANNEL = 'PERFORMER_SOCKET_CONNECTED_CHANNEL';
